:midnight: https://midnight.network/[Midnight]
:nvm: https://github.com/nvm-sh/nvm[nvm]
:yarn: https://yarnpkg.com/getting-started/install[yarn]
:turbo: https://turborepo.com/docs/getting-started/installation[turbo]
:compact-dev-tools: https://docs.midnight.network/blog/compact-developer-tools[Compact Developer Tools]

= Contracts for Compact

*A library for secure smart contract development* written in Compact for {midnight}.
This library consists of modules to build custom smart contracts.

WARNING: This repo contains highly experimental code. Expect rapid iteration. *Use at your own risk.*

== Usage

Make sure you have {nvm} and {yarn} installed on your machine.

Follow Midnight's {compact-dev-tools} installation guide and confirm that `compact` is in the `PATH` env variable.

```bash
$ compact compile --version

Compactc version: 0.25.0
0.25.0
```

=== Installation

Create a directory for your project.

```bash
mkdir my-project
cd my-project
```

Initialize git and add OpenZeppelin Contracts for Compact as a submodule.

```bash
git init && \
git submodule add https://github.com/OpenZeppelin/compact-contracts.git
```

`cd` into it and then install dependencies and prepare the environment.

```bash
nvm install && \
yarn && \
SKIP_ZK=true yarn compact
```

=== Write a custom contract using library modules

In the root of `my-project`, create a custom contract using OpenZeppelin Compact modules.
Import the modules through `compact-contracts/node_modules/@openzeppelin-compact/contracts/...`.
Import modules through `node_modules` rather than directly to avoid state conflicts between shared dependencies.

NOTE: Installing the library will be easier once it's available as an NPM package.

```typescript
// MyContract.compact

pragma language_version >= 0.16.0;

import CompactStandardLibrary;
import "./compact-contracts/node_modules/@openzeppelin-compact/contracts/src/access/Ownable"
  prefix Ownable_;
import "./compact-contracts/node_modules/@openzeppelin-compact/contracts/src/security/Pausable"
  prefix Pausable_;
import "./compact-contracts/node_modules/@openzeppelin-compact/contracts/src/token/FungibleToken"
  prefix FungibleToken_;

constructor(
  _name: Opaque<"string">,
  _symbol: Opaque<"string">,
  _decimals: Uint<8>,
  _recipient: Either<ZswapCoinPublicKey, ContractAddress>,
  _amount: Uint<128>,
  _initOwner: Either<ZswapCoinPublicKey, ContractAddress>,
) {
  Ownable_initialize(_initOwner);
  FungibleToken_initialize(_name, _symbol, _decimals);
  FungibleToken__mint(_recipient, _amount);
}

export circuit transfer(
  to: Either<ZswapCoinPublicKey, ContractAddress>,
  value: Uint<128>,
): Boolean {
  Pausable_assertNotPaused();
  return FungibleToken_transfer(to, value);
}

export circuit pause(): [] {
  Ownable_assertOnlyOwner();
  Pausable__pause();
}

export circuit unpause(): [] {
  Ownable_assertOnlyOwner();
  Pausable__unpause();
}

(...)
```

=== Compile the contract

In the project root, compile the contract using Compact's dev tools.

```bash
% compact compile MyContract.compact artifacts/MyContract
Compiling 3 circuits:
  circuit "pause" (k=10, rows=125)
  circuit "transfer" (k=11, rows=1180)
  circuit "unpause" (k=10, rows=121)
Overall progress [====================] 3/3
```
